
import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import ApolloProvider from "@/shared/provider/apolloProvider";
import Header from "../components/header";
import Footer from "../components/footer";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-merriweather', 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        <ApolloProvider>
          <Header />
        {children}
        <Footer />
        
        </ApolloProvider>
        
      </body>
    </html>
  );
}
