import React from "react";
import type { Metadata } from "next";

import ApolloProvider from "@/shared/provider/apolloProvider";
import Header from "../components/header";
import Footer from "../components/footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        <ApolloProvider>
          <Header />
          {children}
          <Footer />

        </ApolloProvider>
        
      </body>
    </html>
  );
}
